version: '3'

services:
  db:
    image: 'postgres:alpine3.19'
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - ./db/postgresql:/var/lib/postgresql
  app:
    image: 'cotarius/reminder:0.0.7'
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    environment:
      - 'TZ=Europe/Moscow'
      - 'spring_datasource_url=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'