spring:
  application:
    botToken: 5982691328:AAFalCNB5LRCPDU-nRxL_-RGxK3tnl5Sz3o
    name: reminder

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 105117623295-9n3bd4job49hggm6jl198jufqta8372b.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub