spring:
  application:
    botToken: 5982691328:AAFalCNB5LRCPDU-nRxL_-RGxK3tnl5Sz3o
    name: reminder

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: cotarius713@gmail.com
#    password: 1213934montana
#    protocol: smtp
#    properties:
#      tls: true
#      mail:
#        smtp:
#          setTLS: true
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            trust: smtp.gmail.com

#server:
#  tomcat:
#    relaxed-path-chars: \
#    relaxed-query-chars: \